# https://docs.github.com/code-security/dependabot/dependabot-version-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
