# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Michiel on Home Automation"
masthead_title: "Michiel"
logo: "/assets/images/logo.png"
subtitle: "on Home Automation"
email: 
description: >- # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.netk.nl" # the base hostname & protocol for your site, e.g. http://example.com
# github_username: mkarnebeek

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jemoji
  - jekyll-data
  - jekyll-mermaid
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# minimal-mistakes config
locale: "en-US"
#date_format: "%B %Y"
date_format: "%d-%m-%Y"

# giscus
repository: "mkarnebeek/blog.netk.nl"

author:
  name   : "Michiel Karnebeek"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Tech nerd, software developer and father of 2 children. I mainly write about home automation and sometimes about other tech topics."
  links:
    - label: "Feed"
      icon: "fas fa-fw fa-rss"
      url: "https://blog.netk.nl/feed.xml"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://mastodon.social/@mkarnebeek"

footer:
  links:
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://mastodon.social/@mkarnebeek"

include:
  - _pages

tag_archive:
  type: liquid
  path: /posts/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide_post
      author_profile: false
      read_time: true
      comments: true
      show_date: true
      share: false
      toc: true
      toc_sticky: true
      toc_label: "Inhoud"
      related: true
      permalink: /:year/:title/
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _domotica_setup
  - scope:
      path: ""
      type: domotica_setup
    values:
      layout: single
      author_profile: false
      share: false
      toc: true
      toc_sticky: true
      toc_label: "Inhoud"
      sidebar:
        nav: "domotica_setup"

collections:
  domotica_setup:
    output: true
    permalink: /:collection/:path/

comments:
  provider: giscus
  giscus:
    repo_id: "R_kgDOOE8-0g"
    category_name: "Announcements"
    category_id: "DIC_kwDOOE8-0s4CnsTR"
    discussion_term: "pathname"
    reactions_enabled: "1"
    theme: "light"
    lang: "en"

mermaid:
  src: "https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"
